### ISSUE TITLE
StreetRrnCode

### ISSUE THREAD

**Issue by pvdbosch** [belgif/openapi-location#5]
Validate StreetNrCode type by REST design and functional WG.
Promote to v1 if OK

**Comment by pvdbosch** [comment]
OK for REST design WG but concerns over misinterpretation of "Nr" as "number" instead of "national registry". Decision left up to functional WG but same issue discussed there already. StreetNatRegCode could be alternative, but inconsistent with other use of NR abbreviation. Capital Case StreetNRCode is inconsistent with naming conventions.

**Comment by pvdbosch** [comment]
functional WG proposes StreetRrnCode. RRN ( = concatenation of RijksRegister + Registre National) is used by National Registry e.g. in their domain name.
Swagger updated. Awaiting publication of StreetRrnCode as "proposed standard" in new fedvoc vocabularies.

**Comment by smals-chlo** [comment]
Hi @pvdbosch, 
How can I find the Swagger where  StreetRrnCode is updated?

**Comment by pvdbosch** [comment]
Hi @smals-chlo , it's in https://github.com/belgif/openapi-location/blob/master/src/main/swagger/location/v1beta/location-v1beta.yaml . It is in beta until it also has been published in the [fedvoc vocabularies](https://github.com/belgif/fedvoc/blob/master/FederalServicePlatform-Vocabularies.xlsx) but I don't expect any more changes.

**Comment by pvdbosch** [comment]
published in fedvoc and promoted to stable/v1. Will be part of next release.
