### ISSUE TITLE
BelgianPostCode

### ISSUE THREAD

**Issue by pvdbosch** [belgif/openapi-location#7]
Define a schema type for a Belgian post code (4 digits)

https://www.bpost2.be/zipcodes/files/zipcodes_num_nl_new.pdf 

1000-9999; numerical or string?
Or do we include 0612 (Saint Nicolas?)

**Comment by JDMKSZ** [comment]
0612 is never used in administrations (even at BPost it's probably implemented as an exception), I wouldn't add it.
